# Generated by Django 5.2 on 2025-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_electricianservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AC', 'Air Conditioner'), ('WM', 'Washing Machine'), ('RF', 'Refrigerator')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='appliance_services/')),
            ],
        ),
    ]
