# Generated by Django 5.2 on 2025-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cleaningservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='salon_services/')),
                ('gender', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men')], max_length=10)),
            ],
        ),
    ]
