# Generated by Django 5.2 on 2025-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_salonservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='main_services/')),
                ('url_name', models.CharField(help_text="Django URL name for the detail page (e.g., 'electrician', 'appliance')", max_length=50)),
            ],
        ),
    ]
